const ProgrammersData = [
	{
		id: 1,
		first_name: 'FAWAZ ',
		last_name: 'ALQARNI',
		dateOfBirth: '02-04-1992',
		gender: 'Male',
		salary: 400,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/David-Patterson.jpg?w=700&ssl=1',
	},
	{
		id: 2,
		first_name: 'Mohammed ',
		last_name: 'ALOWAIS',
		dateOfBirth: '10-10-1991',
		gender: 'Male',
		salary: 650,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-Carmack.jpg?w=700&ssl=1',
	},
	{
		id: 3,
		first_name: 'Mohammed ',
		last_name: 'Alyami',
		dateOfBirth: '14-08-1997',
		gender: 'Male',
		salary: 215,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Donald-Ervin-Knuth.png?w=700&ssl=1',
	},
	{
		id: 4,
		first_name: 'Alan Mathison ',
		last_name: 'Turing',
		dateOfBirth: '26-01-1997',
		gender: 'Male',
		salary: 400,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Alan-Mathison-Turing.jpg?w=700&ssl=1',
	},
	{
		id: 5,
		first_name: 'Dennis ',
		last_name: 'Ritchie',
		dateOfBirth: '15-01-1997',
		gender: 'Male',
		salary: 500,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Dennis-Ritchie.jpg?w=700&ssl=1',
	},
	{
		id: 6,
		first_name: 'Linus ',
		last_name: 'Torvalds',
		dateOfBirth: '15-09-1992',
		gender: 'Male',
		salary: 210,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Linus-Torvalds.jpg?w=700&ssl=1',
	},
	{
		id: 7,
		first_name: 'Bjarne ',
		last_name: 'Stroustrup',
		dateOfBirth: '25-05-1992',
		gender: 'Male',
		salary: 150,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Bjarne-Stroustrup.jpg?w=700&ssl=1',
	},
	{
		id: 8,
		first_name: 'Tim ',
		last_name: 'Berners-Lee',
		dateOfBirth: ' 11-10-1994',
		gender: 'Male',
		salary: 150,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Tim-Berners-Lee.jpg?w=700&ssl=1',
	},
	{
		id: 9,
		first_name: 'Ken ',
		last_name: 'Thompson',
		dateOfBirth: '12-01-1997',
		gender: 'Male',
		salary: 400,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Ken-Thompson.jpg?w=600&ssl=1',
	},
	{
		id: 10,
		first_name: 'Brian ',
		last_name: 'Kernighan',
		dateOfBirth: ' 01-11-1993',
		gender: 'Male',
		salary: 220,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Brian-Kernighan.jpg?w=700&ssl=1',
	},
	{
		id: 11,
		first_name: 'Bill ',
		last_name: 'Gates',
		dateOfBirth: '02-04-1992',
		gender: 'Male',
		salary: 420,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Bill-Gates.jpg?w=700&ssl=1',
	},
	{
		id: 12,
		first_name: 'John ',
		last_name: 'Backus',
		dateOfBirth: '10-10-1991',
		gender: 'Male',
		salary: 630,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-Backus.jpg?w=700&ssl=1',
	},
	{
		id: 13,
		first_name: 'Grace ',
		last_name: 'Hopper',
		dateOfBirth: '14-08-1997',
		gender: 'Male',
		salary: 275,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Grace-Hopper.jpg?w=700&ssl=1',
	},
	{
		id: 14,
		first_name: 'John George ',
		last_name: 'Kemeny',
		dateOfBirth: '26-01-1997',
		gender: 'Male',
		salary: 408,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-George-Kemeny.jpg?w=700&ssl=1',
	},
	{
		id: 15,
		first_name: 'John ',
		last_name: 'McCarthy',
		dateOfBirth: '15-01-1997',
		gender: 'Male',
		salary: 520,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-McCarthy.jpg?w=700&ssl=1',
	},
	{
		id: 16,
		first_name: 'Thomas Eugene ',
		last_name: 'Kurtz',
		dateOfBirth: '15-09-1992',
		gender: 'Male',
		salary: 500,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Thomas-Eugene-Kurtz.jpg?w=700&ssl=1',
	},
	{
		id: 17,
		first_name: 'Alan Curtis ',
		last_name: 'Kay',
		dateOfBirth: '25-05-1992',
		gender: 'Male',
		salary: 220,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Alan-Curtis-Kay.jpg?w=700&ssl=1',
	},
	{
		id: 18,
		first_name: 'Niklaus ',
		last_name: 'Wirth',
		dateOfBirth: ' 11-10-1994',
		gender: 'Male',
		salary: 260,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Niklaus-Wirth.jpg?w=700&ssl=1',
	},
	{
		id: 19,
		first_name: 'James Arthur ',
		last_name: 'Gosling',
		dateOfBirth: '12-01-1997',
		gender: 'Male',
		salary: 350,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/James-Arthur-Gosling.jpg?w=700&ssl=1',
	},
	{
		id: 20,
		first_name: 'Guido van ',
		last_name: 'Rossum',
		dateOfBirth: ' 01-11-1993',
		gender: 'Male',
		salary: 200,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Guido-van-Rossum.jpg?w=700&ssl=1',
	},
];

export default ProgrammersData;
