const ProgrammersData = [
	{
		id: 1,
		name: 'David Patterson',
		done: 'RISC processor design',
		gender: 'Male',
		demand: 400,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/David-Patterson.jpg?w=700&ssl=1',
	},
	{
		id: 2,
		name: 'John Carmack',
		done: 'video games Doom',
		gender: 'Male',
		demand: 650,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-Carmack.jpg?w=700&ssl=1',
	},
	{
		id: 3,
		name: 'Donald Ervin Knuth',
		done: 'created WEB',
		gender: 'Male',
		demand: 215,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Donald-Ervin-Knuth.png?w=700&ssl=1',
	},
	{
		id: 4,
		name: 'Alan Mathison Turing',
		done: 'PS4',
		gender: 'Male',
		demand: 400,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Alan-Mathison-Turing.jpg?w=700&ssl=1',
	},
	{
		id: 5,
		name: 'Dennis Ritchie',
		done: 'C programming language',
		gender: 'Male',
		demand: 500,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Dennis-Ritchie.jpg?w=700&ssl=1',
	},
	{
		id: 6,
		name: 'Linus Torvalds',
		done: 'Linux kernel code',
		gender: 'Male',
		demand: 210,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Linus-Torvalds.jpg?w=700&ssl=1',
	},
	{
		key: 'B015WXL0C6',
		id: 7,
		name: 'Bjarne Stroustrup',
		done: 'C++ language',
		gender: 'Male',
		demand: 150,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Bjarne-Stroustrup.jpg?w=700&ssl=1',
	},
	{
		id: 8,
		name: 'Tim Berners-Lee',
		done: ' Commander Keen',
		gender: 'Male',
		demand: 150,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Tim-Berners-Lee.jpg?w=700&ssl=1',
	},
	{
		id: 9,
		name: 'Ken Thompson',
		done: 'developed Unix OS',
		gender: 'Male',
		demand: 400,
		position: 'Developer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Ken-Thompson.jpg?w=600&ssl=1',
	},
	{
		id: 10,
		name: 'Brian Kernighan',
		done: 'developed Unix OS',
		gender: 'Male',
		demand: 220,
		position: 'Developer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Brian-Kernighan.jpg?w=700&ssl=1',
	},
	{
		id: 11,
		name: 'Bill Gates',
		done: 'Microsoft',
		gender: 'Male',
		demand: 420,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Bill-Gates.jpg?w=700&ssl=1',
	},
	{
		id: 12,
		name: 'John Backus',
		done: 'developed BNF',
		gender: 'Male',
		demand: 630,
		position: 'Developer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-Backus.jpg?w=700&ssl=1',
	},
	{
		id: 13,
		name: 'Grace Hopper',
		done: 'invented compiler',
		gender: 'Female',
		demand: 275,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Grace-Hopper.jpg?w=700&ssl=1',
	},
	{
		id: 14,
		name: 'John George Kemeny',
		done: 'invented BASIC',
		gender: 'Male',
		demand: 408,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-George-Kemeny.jpg?w=700&ssl=1',
	},
	{
		id: 15,
		name: 'John McCarthy',
		done: 'invented the Garbage Collection method',
		gender: 'Male',
		demand: 520,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-McCarthy.jpg?w=700&ssl=1',
	},
	{
		id: 16,
		name: 'Thomas Eugene Kurtz',
		done: 'developed the BASIC programming language',
		gender: 'Male',
		demand: 500,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Thomas-Eugene-Kurtz.jpg?w=700&ssl=1',
	},
	{
		id: 17,
		name: 'Alan Curtis Kay',
		done: 'GUI',
		gender: 'Male',
		demand: 220,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Alan-Curtis-Kay.jpg?w=700&ssl=1',
	},
	{
		id: 18,
		name: 'Niklaus Wirth',
		done: 'numerous programming languages',
		gender: 'Male',
		demand: 260,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Niklaus-Wirth.jpg?w=700&ssl=1',
	},
	{
		id: 19,
		name: 'James Arthur Gosling',
		done: 'multi-processor version of Unix',
		gender: 'Male',
		demand: 350,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/James-Arthur-Gosling.jpg?w=700&ssl=1',
	},
	{
		id: 20,
		name: 'Guido van Rossum',
		done: 'developed Python',
		gender: 'Male',
		demand: 200,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Guido-van-Rossum.jpg?w=700&ssl=1',
	},
];

export default ProgrammersData;
