const ProgrammersData = [
	{
		id: 1,
		first_name: 'David ',
		last_name: 'Patterson',
		done: 'RISC processor design',
		gender: 'Male',
		salary: 400,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/David-Patterson.jpg?w=700&ssl=1',
	},
	{
		id: 2,
		first_name: 'John ',
		last_name: 'Carmack',
		done: 'video games Doom',
		gender: 'Male',
		salary: 650,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-Carmack.jpg?w=700&ssl=1',
	},
	{
		id: 3,
		first_name: 'Donald Ervin ',
		last_name: 'Knuth',
		done: 'created WEB',
		gender: 'Male',
		salary: 215,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Donald-Ervin-Knuth.png?w=700&ssl=1',
	},
	{
		id: 4,
		first_name: 'Alan Mathison ',
		last_name: 'Turing',
		done: 'PS4',
		gender: 'Male',
		salary: 400,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Alan-Mathison-Turing.jpg?w=700&ssl=1',
	},
	{
		id: 5,
		first_name: 'Dennis ',
		last_name: 'Ritchie',
		done: 'C programming language',
		gender: 'Male',
		salary: 500,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Dennis-Ritchie.jpg?w=700&ssl=1',
	},
	{
		id: 6,
		first_name: 'Linus ',
		last_name: 'Torvalds',
		done: 'Linux kernel code',
		gender: 'Male',
		salary: 210,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Linus-Torvalds.jpg?w=700&ssl=1',
	},
	{
		id: 7,
		first_name: 'Bjarne ',
		last_name: 'Stroustrup',
		done: 'C++ language',
		gender: 'Male',
		salary: 150,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Bjarne-Stroustrup.jpg?w=700&ssl=1',
	},
	{
		id: 8,
		first_name: 'Tim ',
		last_name: 'Berners-Lee',
		done: ' Commander Keen',
		gender: 'Male',
		salary: 150,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Tim-Berners-Lee.jpg?w=700&ssl=1',
	},
	{
		id: 9,
		first_name: 'Ken ',
		last_name: 'Thompson',
		done: 'developed Unix OS',
		gender: 'Male',
		salary: 400,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Ken-Thompson.jpg?w=600&ssl=1',
	},
	{
		id: 10,
		first_name: 'Brian ',
		last_name: 'Kernighan',
		done: 'developed Unix OS',
		gender: 'Male',
		salary: 220,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Brian-Kernighan.jpg?w=700&ssl=1',
	},
	{
		id: 11,
		first_name: 'Bill ',
		last_name: 'Gates',
		done: 'Microsoft',
		gender: 'Male',
		salary: 420,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Bill-Gates.jpg?w=700&ssl=1',
	},
	{
		id: 12,
		first_name: 'John ',
		last_name: 'Backus',
		done: 'developed BNF',
		gender: 'Male',
		salary: 630,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-Backus.jpg?w=700&ssl=1',
	},
	{
		id: 13,
		first_name: 'Grace ',
		last_name: 'Hopper',
		done: 'invented compiler',
		gender: 'Female',
		salary: 275,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i0.wp.com/www.rankred.com/wp-content/uploads/2019/07/Grace-Hopper.jpg?w=700&ssl=1',
	},
	{
		id: 14,
		first_name: 'John George ',
		last_name: 'Kemeny',
		done: 'invented BASIC',
		gender: 'Male',
		salary: 408,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-George-Kemeny.jpg?w=700&ssl=1',
	},
	{
		id: 15,
		first_name: 'John ',
		last_name: 'McCarthy',
		done: 'invented the Garbage Collection method',
		gender: 'Male',
		salary: 520,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/John-McCarthy.jpg?w=700&ssl=1',
	},
	{
		id: 16,
		first_name: 'Thomas Eugene ',
		last_name: 'Kurtz',
		done: 'developed the BASIC programming language',
		gender: 'Male',
		salary: 500,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Thomas-Eugene-Kurtz.jpg?w=700&ssl=1',
	},
	{
		id: 17,
		first_name: 'Alan Curtis ',
		last_name: 'Kay',
		done: 'GUI',
		gender: 'Male',
		salary: 220,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Alan-Curtis-Kay.jpg?w=700&ssl=1',
	},
	{
		id: 18,
		first_name: 'Niklaus ',
		last_name: 'Wirth',
		done: 'numerous programming languages',
		gender: 'Male',
		salary: 260,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i1.wp.com/www.rankred.com/wp-content/uploads/2019/07/Niklaus-Wirth.jpg?w=700&ssl=1',
	},
	{
		id: 19,
		first_name: 'James Arthur ',
		last_name: 'Gosling',
		done: 'multi-processor version of Unix',
		gender: 'Male',
		salary: 350,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/James-Arthur-Gosling.jpg?w=700&ssl=1',
	},
	{
		id: 20,
		first_name: 'Guido van ',
		last_name: 'Rossum',
		done: 'developed Python',
		gender: 'Male',
		salary: 200,
		position: 'Programmer',
		ProgrammerPhoto: 'https://i2.wp.com/www.rankred.com/wp-content/uploads/2019/07/Guido-van-Rossum.jpg?w=700&ssl=1',
	},
];

export default ProgrammersData;
